title: KKWiki
description: KKwiki 테스트 사이트

url: http://kkwiki.tk
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
markdown_ext:  markdown,mkd,mkdn,md
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: 
   twitter: kalkin_7
   facebook: 
   email: kalkin7@gmail.com

google_analytics: ""
