title: KKWiki
description: KKwiki 테스트 사이트

url: http://kkwiki.tk
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: kalkin7
   twitter: kalkin_7
   facebook: kalkin7
   email: kalkin7@gmail.com

google_analytics: ""
